INVESTMENT_WATCHER_TYPES = ["Investment"]
OTHER_WATCHER_TYPES = ["Task", "Birthday"]
WATCHER_TYPES = INVESTMENT_WATCHER_TYPES + OTHER_WATCHER_TYPES
STATEMENT_EVENT_TYPE = "Statement"
DISTRIBUTION_EVENT_TYPE = "Distribution"
WIRE_RECEIPT_EVENT_TYPE = "Wire Receipt"
COMMITMENT_EVENT_TYPE = "Commitment"
INVESTMENT_EVENT_TYPES = [STATEMENT_EVENT_TYPE,
                          DISTRIBUTION_EVENT_TYPE,
                          WIRE_RECEIPT_EVENT_TYPE,
                          COMMITMENT_EVENT_TYPE]
OTHER_EVENT_TYPES = ["Other"]
EVENT_TYPES = INVESTMENT_EVENT_TYPES + OTHER_EVENT_TYPES
CURRENCY_TYPES = ['USD', 'NIS', 'EUR']
CURRENCY_SYMBOLS = ['$', '₪', '€']
WATCHERS_TABLE_NAME = "watcher-ai-watchers"
EVENTS_TABLE_NAME = "watcher-ai-events"
ADVISORS_TABLE_NAME = "watcher-ai-advisors"
PROD_TABLE_NAMES = [WATCHERS_TABLE_NAME,
                    EVENTS_TABLE_NAME, ADVISORS_TABLE_NAME]
WATCHERS_TABLE_NAME_TEST = "watcher-ai-watchers-test"
EVENTS_TABLE_NAME_TEST = "watcher-ai-events-test"
ADVISORS_TABLE_NAME_TEST = "watcher-ai-advisors-test"
TEST_TABLE_NAMES = [WATCHERS_TABLE_NAME_TEST,
                    EVENTS_TABLE_NAME_TEST, ADVISORS_TABLE_NAME_TEST]
COL_NAME = "name"
COL_CURRENCY = "currency"
COL_ID = "id"
COL_PHONE = "phone"
COL_MAIL = "mail"
COL_PARENT_ID = "parent_id"
COL_DATE = "date"
COL_TYPE = "type"
COL_EVENTS_COUNT = "events"
COL_EVENTS = "events"
COL_FINANCE = "finance"
COL_INVESTED = "invested"
COL_ACTIVE = "active"
COL_VALUE = "value"
COL_PROFIT_ITD = "ITD"
COL_PROFIT_YTD = "YTD"
COL_DESCRIPTION = "description"
COL_COMMITMENT = "commited"
COL_UNFUNDED = "unfunded"
COL_DIST_ITD = "Dist-ITD"
COL_DIST_YTD = "Dist-YTD"
ADVISOR_NAME = "advisor"
ROI = "roi"
NET_GAIN = "Net Gain"
YTDP = "YTD%"
ITDP = "ITD%"
IRR = "IRR"
XIRR = "XIRR"
MONTHS = "months"
INT_COLS_TYPE = [COL_VALUE, COL_COMMITMENT, COL_DIST_YTD, COL_DIST_ITD,
                 COL_UNFUNDED, COL_PROFIT_YTD, COL_INVESTED, COL_PROFIT_ITD]
DATE_FORMAT = "%Y-%m-%d"
BACK_TO_MAIN_MENU = "<-- Back"
INVESTMENTS_DOC_DIR = "/Users/nirbejerano/Downloads/investment_docs"
YES = "YES"
NO = "NO"
RET_OK = 0
RET_FAILED = -1
